### ISSUE TITLE
Unset local-path as default storage class

### ISSUE THREAD

**Issue by minhtt159** [minhtt159/fruitsap#214]
# Details

**Describe the solution you'd like:**

Configuration that allows setting local-path is not a default storage-class

**Anything else you would like to add:**

I know that you can disable local-path entirely in ansible but I just want it not to be default storage class, still want to use it in case of any pod that wants local volume

**Additional Information:**

`provision/ansible/inventory/group_vars/master/k3s.yml`

```
# (dict) k3s settings for all control-plane nodes
k3s_server:
  node-ip: "{{ ansible_host }}"
  tls-san:
    # kube-vip
    - "{{ kubevip_address }}"
  # Disable Docker - this will use the default containerd CRI
  docker: false
  flannel-backend: "none" # This needs to be in quotes
  disable:
    # Disable local-path-provider - if using alternative storageClass (longhorn, nfs-subdir-external-provisioner, etc)
    - local-storage
```
